name: Node.js CI

on: push
    
jobs:
  build:
  
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
        
    steps:
    - name: My first step
      env:
        MY_VAR: Hi there! My name is
        FIRST_NAME: BELLICOSE
        MIDDLE_NAME: TRAIN
        LAST_NAME: ASSASSIN
      run: echo $FIRST_NAME $MIDDLE_NAME $LAST_NAME
    - name: my second step
      if: success()
      run: echo "The previous step has finished successfully"
    - name: my third step
      uses: actions/checkout@v1
      with:
        node-version: 12
        registry-url: https://npm.pkg.github.com/
